# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kgv Am Wäldchen

description: >- # this means to ignore newlines until "baseurl:"
  Inoffizielle Seite des Kleingartenvereins "Am Wäldchen e.V."
baseurl: "/kgv-am-waeldchen" # the subpath of your site, e.g. /blog
url: "https://am-waeldchen.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
color_scheme: green
remote_color_scheme: green

search_enabled: false
favicon_ico: "/assets/favicon.ico"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
